import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { ViewTransitions } from "next-view-transitions";
import AppShell from "./appShell";



export const metadata: Metadata = {
  title: "Opajobi dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
   <html
      lang="en"
    >
      <body className="relative">
      <AppShell>
         <Header/>
         {children}
         <Footer/>
         </AppShell>
      </body>
    </html>
    </ViewTransitions>
 
  );
}
