import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { ViewTransitions } from "next-view-transitions";
import AppShell from "./appShell";

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  variable: "--font-funnel",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Opajobi dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${funnelSans.variable}`}
      >
        <body className="relative">
          <AppShell>
            <Header />
            {children}
            <Footer />
          </AppShell>
        </body>
      </html>
    </ViewTransitions>
  );
}